#%RAML 1.0
title: item
version: v1
protocols:
  - https
description: These APIs are used to performe operations on item in the ABC system.

/customer/invoice/item:
  post:
    body:
      application/json:
        type: !include /datatypes/pdataType.raml
        example: !include /examples/request post.json
    responses:
      200:
        body:
          application/json:
            example: !include/examples/response post.json
      404:
        description: |
          id not found  
  put:
    body:
      application/json:
        type: !include datatypes/putdataType.raml
        example: !include examples/1-request put.json
    responses:
      200:
        body:
          application/json:
            example: !include /examples/1-response put.json
      400:
        description: |
          not found 
